### PR TITLE
issue#4 completed

### PR DESCRIPTION
**Pull request by alextor2625**
Added required to email and password for User schema

Added trim to fullname, email and password for User schema.

Added US Passport number for User schema

### CODE REVIEW

**Review by AlfG71 — COMMENTED** [review]
Thank you for adding the passport number!  

But we do need to add two separate fields in addition to Voter registration number and License number.  The reason is that for donations, the user will have 5 different options to enter as a valid identification number and we need to keep track of all of them.

So the remaining properties need to be added before we do the pull request.  

Those properties being:
- US Voter registration number
- US License number

Thank you for taking this on guys!

**Comment by alextor2625** [comment]
Thanks for the feedback Alfonso.
In terms of the remaining properties, they seemed to already be implemented into the User Schema already so we just added the missing property which was US Passport Number.

image_2024-01-27_222707463

**Comment by alextor2625** [comment]
If you want different types of ways to identify someone couldn't we merge the voterRegistrationNumber, driversLicenceNumber and Us Passport Number as a single property named identification and save them as an object to try and differentiate what identification they are using?

For example:

`identification{
    type: "US Passport",
    number: "555555555"
}`

**Comment by AlfG71** [comment]
That could be an approach as well.  Give it a try and let's see what it looks like.  Please try naming things as detailed as possible.  

ie. `typeOfIdentificationUsed: { type: "[nameOfTheTypeOfId]", number: "1234" }`

The square brackets in the example `[ ]` are a placeholder.  Let me know if it does not make sense

**Comment by alextor2625** [comment]
Alfonso I pushed a new version of this branch. Basically I modified the User Schema so that it has a few sub schemas to manage identification and address so that they are both stored in an object format. I included the address in this change since we wanted both the identification and address to be stored as an object format I thought I might as well do include it in the change. Here is an example of how a document would look like:

`{
  "_id": ...,
  "fullName": "John Doe",
  "email": "john@example.com",
  "password": "hashedpassword",
  "userName": "johndoe",
  "phoneNumber": "123456789",
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zip": "12345"
  },
  "identification": {
    "identificationType": "US Passport",
    "identificationNumber": "123456789"
  },
  "volunteer": true,
  "donations": [],
  "eventsAttended": [],
  "createdAt": ...,
  "updatedAt": ...
}`

I would appreciate any feedback you have on this. Thanks.

**Pull request closed without merging**
